CREATE TABLE `comment` (
                           `comment_seq` bigint NOT NULL AUTO_INCREMENT,
                           `post_seq` bigint NOT NULL,
                           `content` text NOT NULL,
                           `insert_ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           `delete_flag` tinyint(1) DEFAULT '0',
                           `delete_ts` timestamp NULL DEFAULT NULL,
                           `parent_comment_seq` bigint DEFAULT NULL,
                           `user_seq` bigint NOT NULL,
                           `reply_user_seq` bigint DEFAULT NULL,
                           PRIMARY KEY (`comment_seq`),
                           KEY `comment_ibfk_1` (`post_seq`),
                           KEY `comment_ibfk_2` (`parent_comment_seq`),
                           KEY `comment_ibfk_3` (`user_seq`),
                           KEY `comment_ibfk_4` (`reply_user_seq`),
                           CONSTRAINT `comment_ibfk_1` FOREIGN KEY (`post_seq`) REFERENCES `post` (`post_seq`) ON DELETE CASCADE,
                           CONSTRAINT `comment_ibfk_2` FOREIGN KEY (`parent_comment_seq`) REFERENCES `comment` (`comment_seq`) ON DELETE CASCADE,
                           CONSTRAINT `comment_ibfk_3` FOREIGN KEY (`user_seq`) REFERENCES `user` (`user_seq`) ON DELETE CASCADE,
                           CONSTRAINT `comment_ibfk_4` FOREIGN KEY (`reply_user_seq`) REFERENCES `user` (`user_seq`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci